#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
upstream_url=${SUITESPARSE_UPSTREAM_URL:-https://github.com/DrTimothyAldenDavis/SuiteSparse.git}
upstream_ref=${1:-dev}
tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/camd-sync.XXXXXX")
trap 'find "$tmpdir" -depth -delete' EXIT

git clone --quiet --depth=1 --filter=blob:none --sparse \
    --branch "$upstream_ref" "$upstream_url" "$tmpdir"
git -C "$tmpdir" sparse-checkout set CAMD SuiteSparse_config

mkdir -p "$repo_root/include" "$repo_root/src/upstream" \
    "$repo_root/tests/upstream"
rsync -a --delete "$tmpdir/CAMD/Source/" "$repo_root/src/upstream/"
install -m 0644 "$tmpdir/CAMD/Include/camd.h" "$repo_root/include/camd.h"
install -m 0644 "$tmpdir/CAMD/Include/camd_internal.h" \
    "$repo_root/src/upstream/camd_internal.h"
rsync -a --delete --include='*.c' --include='*.out' --exclude='*' \
    "$tmpdir/CAMD/Demo/" "$repo_root/tests/upstream/"
install -m 0644 "$tmpdir/CAMD/Doc/License.txt" "$repo_root/LICENSE"

config_header="$tmpdir/SuiteSparse_config/SuiteSparse_config.h"
suitesparse_date=$(sed -n 's/^#define SUITESPARSE_DATE //p' "$config_header")
suitesparse_major=$(awk '$2 == "SUITESPARSE_MAIN_VERSION" {print $3}' "$config_header")
suitesparse_minor=$(awk '$2 == "SUITESPARSE_SUB_VERSION" {print $3}' "$config_header")
suitesparse_patch=$(awk '$2 == "SUITESPARSE_SUBSUB_VERSION" {print $3}' "$config_header")
cat > "$repo_root/include/SuiteSparse_config_version.h" <<EOF
// Generated by scripts/sync-upstream.sh from SuiteSparse_config.
// SPDX-License-Identifier: BSD-3-Clause

#ifndef SUITESPARSE_CONFIG_VERSION_H
#define SUITESPARSE_CONFIG_VERSION_H

#define SUITESPARSE_DATE $suitesparse_date
#define SUITESPARSE_MAIN_VERSION $suitesparse_major
#define SUITESPARSE_SUB_VERSION $suitesparse_minor
#define SUITESPARSE_SUBSUB_VERSION $suitesparse_patch

#endif
EOF

commit=$(git -C "$tmpdir" rev-parse HEAD)
commit_date=$(git -C "$tmpdir" show -s --format=%cs HEAD)
camd_version=$(awk \
    '/CAMD_MAIN_VERSION/{major=$3} /CAMD_SUB_VERSION/{minor=$3} /CAMD_SUBSUB_VERSION/{patch=$3} END{print major "." minor "." patch}' \
    "$repo_root/include/camd.h")

printf '%s\n' \
    "repository=$upstream_url" \
    "ref=$upstream_ref" \
    "commit=$commit" \
    "commit_date=$commit_date" \
    "camd_version=$camd_version" \
    > "$repo_root/UPSTREAM"

printf 'Synced CAMD %s from SuiteSparse %s (%s).\n' \
    "$camd_version" "${commit:0:12}" "$commit_date"
