// Generated by scripts/sync-upstream.sh from SuiteSparse_config.
// SPDX-License-Identifier: BSD-3-Clause

#ifndef SUITESPARSE_CONFIG_VERSION_H
#define SUITESPARSE_CONFIG_VERSION_H

#define SUITESPARSE_DATE "Aug 10, 2026"
#define SUITESPARSE_MAIN_VERSION 7
#define SUITESPARSE_SUB_VERSION 13
#define SUITESPARSE_SUBSUB_VERSION 0

#endif
