// Generated by scripts/sync-upstream.sh from SuiteSparse_config.
// SPDX-License-Identifier: BSD-3-Clause

#ifndef SUITESPARSE_CONFIG_VERSION_H
#define SUITESPARSE_CONFIG_VERSION_H

#define SUITESPARSE_DATE "July 31, 2026"
#define SUITESPARSE_MAIN_VERSION 7
#define SUITESPARSE_SUB_VERSION 12
#define SUITESPARSE_SUBSUB_VERSION 3

#endif
